# Generated by Django 5.0.7 on 2024-09-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0007_employees_gestorcliente_employees_gestorextractta'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salaryVC',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='employees',
            name='tipoBeneficio',
            field=models.IntegerField(default=0),
        ),
    ]
